Resources:
  CatalogItemsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:service}-catalogItems-queue
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt CatalogItemsDLQ.Arn
        maxReceiveCount: 5

  CatalogItemsDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:service}-catalogItems-dlq
