service: 'import-service'

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    PRODUCTS_FILES_BUCKET: ${self:custom.params.productsFilesBucket}
    PRODUCTS_SQS_URL: ${self:custom.params.productsSqsUrl}

plugins:
  - serverless-webpack

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    packager: 'yarn'
    includeModules: true
  params:
    productsFilesBucket: products-files-bucket
    productsSqsUrl: ${ssm:products_sqs_url}

package:
  individually: true
  excludeDevDependencies: true

functions:
  - ${file(./sls/functions/importFileParser.yml)}
  - ${file(./sls/functions/importProductsFile.yml)}

resources:
  - ${file(./sls/resources/iam.yml)}
